### PR TITLE
Fix CSRG mappings parsing

### LINKED ISSUE #17: Fields won't be renamed with csrg mappings
Hi there (again),

I am trying to deobfuscate a 1.12.2 jar. The first step (renaming mojangs to the static names from mcp) fails partly. The classes will be renamed, all fine, but no fields.

The mappings looks like this:
```
a net/minecraft/util/text/TextFormatting
	a BLACK
	b DARK_BLUE
	c DARK_GREEN
	d DARK_AQUA
	e DARK_RED
	f DARK_PURPLE
	g GOLD
	h GRAY
	i DARK_GRAY
	j BLUE
	k GREEN
	l AQUA
	m RED
	n LIGHT_PURPLE
	o YELLOW
	p WHITE
	q OBFUSCATED
	r BOLD
	s STRIKETHROUGH
	t UNDERLINE
	u ITALIC
	v RESET
	w field_96331_x
	x field_96330_y
	y field_175748_y
	z field_96329_z
	A field_96303_A
	B field_96304_B
	C field_175747_C
	D $VALUES
	a (I)La; func_175744_a
	a (Ljava/lang/String;)Ljava/lang/String; func_110646_a
	a (ZZ)Ljava/util/Collection; func_96296_a
	b ()I func_175746_b
	b (Ljava/lang/String;)La; func_96300_b
	c ()Z func_96301_b
	c (Ljava/lang/String;)Ljava/lang/String; func_175745_c
	d ()Z func_96302_c
	e ()Ljava/lang/String; func_96297_d
	values ()[La; values
	toString ()Ljava/lang/String; toString
```

I tried it with: `./MC-Remapper --output-name=1.12.2/static.jar --fixlocalvar=rename --format=csrg 1.12.2/client.jar 1.12.2/staticMap.srg --reobf`

Also tried it without `--fixlocalvar`, but also no success (just for running it with minimal arguments, I doubt removing this helps).

I hope you can help me :)

Thanks

Moritz

### PR DESCRIPTION
**Pull request by Bixilon**
For more details look at #17 

Fixes #17

### CODE REVIEW

**Comment by Bixilon** [comment]
I am just seeing, that v1 is the same as v2...lol. I'll fix it soon

**Comment by Bixilon** [comment]
So, the todo was not necessary, it works and I merged both formats. The check from CodeFactor is not an issue (I'd say), I split in in functions, but these functions are in a function, so that fails the check.

**Comment by Bixilon** [comment]
Any progress?

**Comment by HeartPattern** [comment]
I forgot to handle it. Thanks for your contribution!

**Pull request merged**
